name       : hunspell-hu
version    : 1.6.1
release    : 3
source     :
    - http://downloads.sourceforge.net/magyarispell/hu_HU-1.6.1.tar.gz : 0a1ab4672bf75acc1c29c4b3fbcab5d10b7883ba1e7fc25e8054d2209f0352c2
homepage   : https://magyarispell.sourceforge.net/
license    : GPL-2.0-or-later
component  : office.spelling
summary    : Hungarian hunspell dictionaries
description: |
    Hungarian hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -Ddm00755 $installdir/usr/share/hunspell
    install -m00644 hu_HU.dic hu_HU.aff $installdir/usr/share/hunspell
