name       : hunspell-hu
version    : 1.6.1
release    : 1
source     :
    - http://heanet.dl.sourceforge.net/project/magyarispell/Magyar%20Ispell/1.6.1/hu_HU-1.6.1.tar.gz : 0a1ab4672bf75acc1c29c4b3fbcab5d10b7883ba1e7fc25e8054d2209f0352c2
license    : GPL-2.0
component  : spelling
summary    : Hungarian hunspell dictionaries
description: |
    Hungarian hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -d -m 00644 $installdir/usr/share/hunspell
    install -m 00644 hu_HU.dic hu_HU.aff $installdir/usr/share/hunspell